<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <UserSecretsId>964982f8-95e7-4bcb-897a-f93c19340f9f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="Domain\Sales\Model\**" />
    <Compile Remove="Domain\ServiceItens\Model\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Domain\Sales\Model\**" />
    <Content Remove="Domain\ServiceItens\Model\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Domain\Sales\Model\**" />
    <EmbeddedResource Remove="Domain\ServiceItens\Model\**" />
    <None Remove="Controllers\**" />
    <None Remove="Domain\Sales\Model\**" />
    <None Remove="Domain\ServiceItens\Model\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
    <PackageReference Include="QuestPDF" Version="2024.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\Sales\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
